### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by lexar** [billy1380/JavaEPFImporter#9]
Sorry if that is obvious, but how do I compile a jar? My java knowledge is rusty, I'm used to javac and ant.

**Comment by billy1380** [comment]
You should be able to build it using maven (you will need a version of maven installed on your system). I would strongly advise you to download either eclipse or netbeans though... import the pom... and just run it from the ide.

But if you just want to build it, run `mvn compile`.

**Comment by lexar** [comment]
Thank you for your quick help! I got it working with macports mvn and Netbeans!

**Comment by billy1380** [comment]
Perfect... glad to hear it.
